# This is the manual way of checking out a branch 
name: Checkout Workflow
on: [push]

jobs: 
   checout-and-display-files:
      runs-on: ubuntu-latest
      steps:
         - name: List Files
           run: ls -a
         - name: Checkout
           run: |
            git init
            git remote add origin "https://$GITHUB_ACTOR:{{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
            git fetch origin
            git checkout main
         - name: List files after 
           run: ls -a

