# This is the manual way of checking out a branch 
name: Checkout Workflow
on: [push]

jobs: 

   auto-checkout-action:
      runs-on: ubuntu-latest|
      steps: 
         - name: List Files Before 
           run: ls -a
         - uses: actions/checkout@v3

         - name: List Files After 
           run: ls -a

   manual-checkout-and-display-files:
      runs-on: ubuntu-latest
      steps:
       
         - name: Checkout
           run: |
            git init
            git remote add origin "https://$GITHUB_ACTOR:{{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
            git fetch origin
            git checkout main
         - name: List files after 
           run: ls -a

